name: Ne.app ADB Linux [BUILD]

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  BUILD_TYPE: AVKON_BUILD

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Attempt APT install.
      run: sudo apt upgrade -y && sudo apt update
    - name: Attempt Boost install.
      run: sudo apt install libboost-dev libtbb-dev
