name: Ne.app ADB Windows [BUILD]

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  BUILD_TYPE: AVKON_BUILD

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Attempt APT install.
      run: echo "DONE"